spring:
  datasource:
#    mysql8.0 42.193.48.70主机上3307数据库（正式上线） ---> 添加完数据后要重启服务器
    url: jdbc:mysql://42.193.48.70:3307/grade

#    本地数据库（测试）
#    url: jdbc:mysql://localhost:3306/grade

#    mysql5.7
#    url: jdbc:mysql://124.70.41.214:3306/blue?useUnicode=true&characterEncoding=utf8&useSSL=false

    username: root
    password: Hh18780544808
#    可以不写全局配置文件，所有的配置都放置在属性configuration下
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
##  mybatis可以不使用xml文件
#configuration:
#  map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
